name: Context

on: [push]
jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: |
          echo "Hello! $GITHUB_ACTION"
          echo "Hello! $GITHUB_ACTOR"
        env:
          GITHUB_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}
