name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use API Key
        run: |
          echo "Using API key: ${{ secrets.API_KEY }}"
        env:
          API_KEY: ${{ secrets.API_KEY }}
